all:	0018-hexadecimal-conversion 0003a-exercise \
	0007-exercise-for-loop \
	0008-fizz-buzz \
	0012-exercise-functions

0018-hexadecimal-conversion:	0018-hexadecimal-conversion.c
	cc -W -Wall -o 0018-hexadecimal-conversion 0018-hexadecimal-conversion.c

0003a-exercise:	0003a-exercise.c
	cc -W -Wall -o 0003a-exercise 0003a-exercise.c

0007-exercise-for-loop:	0007-exercise-for-loop.c
	cc -W -Wall -o 0007-exercise-for-loop 0007-exercise-for-loop.c

0008-fizz-buzz:	0008-fizz-buzz.c
	cc -W -Wall -o 0008-fizz-buzz 0008-fizz-buzz.c

0012-exercise-functions:	0012-exercise-functions.c
	cc -W -Wall -o 0012-exercise-functions 0012-exercise-functions.c

