all:	0018-hexadecimal-conversion 0003a-exercise \
	0007-exercise-for-loop \
	0008-fizz-buzz \
	0012-exercise-functions \
	0014-perspective-projection \
	0099a1-adventure \
	0099a2-adventure \
	0099a3-adventure \
	0099a4-adventure

0018-hexadecimal-conversion:	0018-hexadecimal-conversion.c
	cc -g -W -Wall -o 0018-hexadecimal-conversion 0018-hexadecimal-conversion.c

0003a-exercise:	0003a-exercise.c
	cc -g -W -Wall -o 0003a-exercise 0003a-exercise.c

0007-exercise-for-loop:	0007-exercise-for-loop.c
	cc -g -W -Wall -o 0007-exercise-for-loop 0007-exercise-for-loop.c

0008-fizz-buzz:	0008-fizz-buzz.c
	cc -g -W -Wall -o 0008-fizz-buzz 0008-fizz-buzz.c

0012-exercise-functions:	0012-exercise-functions.c
	cc -g -W -Wall -o 0012-exercise-functions 0012-exercise-functions.c

0014-perspective-projection:	0014-perspective-projection.c
	cc -g -W -Wall -o 0014-perspective-projection 0014-perspective-projection.c

0099a1-adventure: 0099a1-adventure.c
	cc -g -W -Wall -o 0099a1-adventure 0099a1-adventure.c

0099a2-adventure: 0099a2-adventure.c
	cc -g -W -Wall -o 0099a2-adventure 0099a2-adventure.c

0099a3-adventure: 0099a3-adventure.c
	cc -g -W -Wall -o 0099a3-adventure 0099a3-adventure.c

0099a4-adventure: 0099a4-adventure.c
	cc -g -W -Wall -o 0099a4-adventure 0099a4-adventure.c

clean:
	rm -f 0018-hexadecimal-conversion \
	0003a-exercise \
	0007-exercise-for-loop \
	0008-fizz-buzz \
	0012-exercise-functions \
	0014-perspective-projection \
	0099a1-adventure \
	0099a2-adventure \
	0099a3-adventure \
	0099a4-adventure
