all:	0018-hexadecimal-conversion 0003a-exercise

0018-hexadecimal-conversion:	0018-hexadecimal-conversion.c
	cc -W -Wall -o 0018-hexadecimal-conversion 0018-hexadecimal-conversion.c

0003a-exercise:	0003a-exercise.c
	cc -W -Wall -o 0003a-exercise 0003a-exercise.c

