CFLAGS=-W -Wall

PRODUCTS=0001-hello 0002-integer-variables \
	0003-variable-types \
	0004-assignment-statement \
	0005-bitwise-operators \
	0006-relational-operators

all:	${PRODUCTS}

clean:
	rm -f ${PRODUCTS}	
