CFLAGS=-W -Wall

PRODUCTS=0001-hello 0002-integer-variables \
	0003-variable-types \
	0004-assignment-statement \
	0005-bitwise-operators \
	0006-relational-operators \
	0007-for-loop \
	0008-if-statement \
	0009-while-loop \
	0010-do-while \
	0011-functions \
	0012-functions

all:	${PRODUCTS}

clean:
	rm -f ${PRODUCTS}	
